import 'dart:math';

class Phrase {
  final List<String> loadingPhrases = [
    "Analyzing your 'incomparable' taste… hold tight.",
    "Scanning the endless void of mediocre movies…",
    "Matching your mood… if it exists, somewhere…",
    "Fetching 'perfect' cinematic gems… theoretically…",
    "Almost done… brilliance takes time…",
    "Evaluating your taste… it's complicated, we know…",
    "Finding movies worthy of your attention… maybe…",
    "One sec… consulting the film oracles…"
  ];

  final List<String> sarcasticTexts = [
    "Oh look, another 'masterpiece' for your refined palate",
    "Because clearly, this is exactly what you needed today",
    "Your next obsession awaits… allegedly",
    "Behold! Cinema that might actually hold your attention",
    "Another movie to add to your 'I'll watch it someday' list"
  ];
  String getRandomMoviePhrase() {
    const List<String> phrases = [
      "Sure, keep scrolling… or watch something actually fun.",
      "Your couch called, it’s lonely without popcorn.",
      "Another cat video? Or a real movie for a change?",
      "Yeah, binge Netflix… or try CineMind like a rebel.",
      "Pretend you’re busy… or just watch this amazing film.",
      "Life’s short. Watch something better than your life choices.",
      "Ignore this, your boredom will thank you… maybe.",
      "Because staring at your phone won’t give you thrills.",
      "Your future self might actually thank you for this pick.",
      "Another mediocre series? Or an actual cinematic gem?",
      "Warning: watching this may improve your taste.",
      "CineMind: the app your other apps envy.",
      "Yes, your notifications deserve this drama.",
      "Skip this, but your fun will suffer.",
      "Stop pretending you have free time… use it wisely.",
      "Because someone has to pick better movies for you.",
      "Your life called. It said ‘watch a good movie!’",
      "Sure, scroll Instagram… or scroll into something epic.",
      "Another cat video? Bold choice.",
      "Maybe try CineMind. Or don’t. You’ll regret it.",
      "Your boredom is begging for this.",
      "Oh look, a movie you’ll actually love.",
      "Because your friends aren’t always right about movies.",
      "Click here… or continue regretting life choices.",
      "The app that actually improves evenings.",
      "Popcorn not included. Thrills guaranteed.",
      "Watch this… or continue your thrilling spreadsheet life.",
      "Who needs reality when movies exist?",
      "Another bad choice? CineMind won’t let it happen.",
      "Sure, scroll TikTok… or scroll something worthwhile.",
      "Your inner movie critic is judging your indecision.",
      "Step into CineMind… unless fear holds you back.",
      "Caution: may ruin other movie apps for you.",
      "Yes, this is exactly the notification you needed.",
      "Ignore it… but don’t complain later.",
      "Your boredom called, it’s screaming.",
      "Popcorn? Check. Sarcasm? Check. CineMind? Obvious.",
      "The perfect movie exists… go find it.",
      "Yes, your couch misses you.",
      "Your life choices may be mediocre… your movie choices don’t have to be.",
      "Clicking this may cause happiness.",
      "Stop pretending you don’t have time for greatness.",
      "Because Netflix autoplay won’t save you.",
      "Your thumbs need a workout. Tap here.",
      "Another cat video? Bold move, champ.",
      "This is the cinematic pick you secretly needed.",
      "Skip this, continue your scrolling misery.",
      "Sure, watch another fail video… or not.",
      "Your boredom will beg for mercy.",
      "Click it… or live with FOMO.",
      "Because life’s too short for bad movies.",
      "Stop wasting time, start living… in movies.",
      "Another day, another bad choice… fix it now.",
      "Your couch approves this message.",
      "Yes, you. Open the app. Go on.",
      "Popcorn is judging you. CineMind isn’t.",
      "You could scroll, or you could be entertained.",
      "Your social life called. It’s jealous of your movie time.",
      "Warning: may cause extreme enjoyment.",
      "Sure, ignore it… see how that works out.",
      "The thrill of cinema awaits… if you dare.",
      "Another cat meme? Bold. CineMind? Smarter.",
      "Because your boredom deserves punishment.",
      "Tap it. Live a little.",
      "Your evening is wasted without this.",
      "Clicking this will improve your life. Maybe.",
      "Don’t. But then regret it loudly later.",
      "Because your couch demands quality content.",
      "Another bad choice? CineMind says no.",
      "Your free time isn’t getting any younger.",
      "Yes, open it. Resistance is futile.",
      "Your inner critic is cheering silently.",
      "Click or don’t. Your call… but poor choice.",
      "The popcorn is ready. Are you?",
      "Sure, scroll memes… or be epic for once.",
      "This is the notification that changes everything.",
      "Your boredom doesn’t stand a chance.",
      "CineMind: because reality is overrated.",
      "Tap here or keep suffering mediocrity.",
      "Another day, another mediocre scroll. Fix it now.",
      "Your friends are probably wrong about movies. Trust us.",
      "Ignore this, and regret nothing less.",
      "Your free time is valuable… CineMind knows it.",
      "Another cat video? Bold. Another CineMind pick? Genius.",
      "Clicking this may cause envy from friends.",
      "Sure, scroll TikTok… CineMind laughs silently.",
      "Life’s short. Tap now.",
      "Yes, you need this sarcasm and this movie.",
      "Ignore at your own peril.",
      "Your boredom is screaming. Finally, relief.",
      "Stop scrolling. Start watching.",
      "CineMind: the app you pretend to know about.",
      "Click or continue your mundane existence.",
      "Your evening is about to be legendary. Maybe.",
      "Another notification? Bold. Another must-watch? Smarter.",
      "Yes, ignore this… if you hate fun.",
      "Because movies > bad choices.",
      "Your couch sends its regards. Tap it.",
      "Sure, scroll endlessly… or do something epic.",
      "Tap now or live with FOMO forever.",
      "Another cat video? Bold. Another CineMind win? Genius."
    ];

    final random = Random();
    return phrases[random.nextInt(phrases.length)];
  }
}
